export interface Tool {
  id: string
  name: string
  description: string
  category: "pdf" | "image" | "file" | "text"
  slug: string
  popular?: boolean
}

export const toolsData = {
  featuredTools: [
    {
      id: "1",
      name: "PDF Merger",
      description: "Combine multiple PDFs into one",
      category: "pdf",
      slug: "pdf-merger",
      popular: true,
    },
    {
      id: "2",
      name: "Image Resizer",
      description: "Resize your images easily",
      category: "image",
      slug: "image-resizer",
      popular: true,
    },
    {
      id: "3",
      name: "File Converter",
      description: "Convert between file formats",
      category: "file",
      slug: "file-converter",
      popular: true,
    },
    {
      id: "4",
      name: "PDF to Word",
      description: "Convert PDF to editable Word",
      category: "pdf",
      slug: "pdf-to-word",
      popular: true,
    },
    {
      id: "5",
      name: "Image Compressor",
      description: "Reduce image file size",
      category: "image",
      slug: "image-compressor",
      popular: true,
    },
    {
      id: "6",
      name: "ZIP Extractor",
      description: "Extract files from ZIP archives",
      category: "file",
      slug: "zip-extractor",
    },
    {
      id: "7",
      name: "PDF Splitter",
      description: "Split PDF into multiple files",
      category: "pdf",
      slug: "pdf-splitter",
    },
    {
      id: "8",
      name: "Image to PDF",
      description: "Convert images to PDF format",
      category: "image",
      slug: "image-to-pdf",
    },
    {
      id: "9",
      name: "File Encryptor",
      description: "Encrypt your sensitive files",
      category: "file",
      slug: "file-encryptor",
    },
    { id: "10", name: "PDF Editor", description: "Edit text and images in PDFs", category: "pdf", slug: "pdf-editor" },
    {
      id: "11",
      name: "Image Cropper",
      description: "Crop your images precisely",
      category: "image",
      slug: "image-cropper",
    },
    {
      id: "12",
      name: "File Organizer",
      description: "Organize files by type and date",
      category: "file",
      slug: "file-organizer",
    },
  ],

  pdfTools: [
    {
      id: "p1",
      name: "PDF Merger",
      description: "Combine multiple PDFs into one",
      category: "pdf",
      slug: "pdf-merger",
      popular: true,
    },
    {
      id: "p2",
      name: "PDF Splitter",
      description: "Split PDF into multiple files",
      category: "pdf",
      slug: "pdf-splitter",
    },
    { id: "p3", name: "PDF Compressor", description: "Reduce PDF file size", category: "pdf", slug: "pdf-compressor" },
    {
      id: "p4",
      name: "PDF to Word",
      description: "Convert PDF to editable Word",
      category: "pdf",
      slug: "pdf-to-word",
      popular: true,
    },
    {
      id: "p5",
      name: "PDF to Excel",
      description: "Convert PDF to Excel spreadsheet",
      category: "pdf",
      slug: "pdf-to-excel",
    },
    { id: "p6", name: "PDF to PPT", description: "Convert PDF to PowerPoint", category: "pdf", slug: "pdf-to-ppt" },
    { id: "p7", name: "PDF to JPG", description: "Convert PDF pages to images", category: "pdf", slug: "pdf-to-jpg" },
    {
      id: "p8",
      name: "Add Page Numbers",
      description: "Add page numbers to PDF",
      category: "pdf",
      slug: "add-page-numbers",
    },
    { id: "p9", name: "PDF Editor", description: "Edit text and images in PDFs", category: "pdf", slug: "pdf-editor" },
    {
      id: "p10",
      name: "PDF Annotator",
      description: "Add notes and comments to PDF",
      category: "pdf",
      slug: "pdf-annotator",
    },
    {
      id: "p11",
      name: "PDF Form Filler",
      description: "Fill PDF forms easily",
      category: "pdf",
      slug: "pdf-form-filler",
    },
    {
      id: "p12",
      name: "PDF Signer",
      description: "Add digital signatures to PDF",
      category: "pdf",
      slug: "pdf-signer",
    },
  ],

  imageTools: [
    {
      id: "i1",
      name: "Image Resizer",
      description: "Resize your images easily",
      category: "image",
      slug: "image-resizer",
      popular: true,
    },
    {
      id: "i2",
      name: "Image Cropper",
      description: "Crop your images precisely",
      category: "image",
      slug: "image-cropper",
    },
    {
      id: "i3",
      name: "Convert to JPG",
      description: "Convert images to JPG format",
      category: "image",
      slug: "convert-to-jpg",
    },
    {
      id: "i4",
      name: "Convert to PNG",
      description: "Convert images to PNG format",
      category: "image",
      slug: "convert-to-png",
    },
    {
      id: "i5",
      name: "Image to PDF",
      description: "Convert images to PDF format",
      category: "image",
      slug: "image-to-pdf",
    },
    {
      id: "i6",
      name: "Image Compressor",
      description: "Reduce image file size",
      category: "image",
      slug: "image-compressor",
      popular: true,
    },
    {
      id: "i7",
      name: "Add Watermark",
      description: "Add watermark to images",
      category: "image",
      slug: "add-watermark",
    },
    {
      id: "i8",
      name: "Remove Background",
      description: "Remove image backgrounds",
      category: "image",
      slug: "remove-background",
    },
    {
      id: "i9",
      name: "Image Enhancer",
      description: "Enhance image quality",
      category: "image",
      slug: "image-enhancer",
    },
    { id: "i10", name: "Image Rotator", description: "Rotate images easily", category: "image", slug: "image-rotator" },
    {
      id: "i11",
      name: "Image Flipper",
      description: "Flip images horizontally or vertically",
      category: "image",
      slug: "image-flipper",
    },
    {
      id: "i12",
      name: "Image Effects",
      description: "Apply effects to images",
      category: "image",
      slug: "image-effects",
    },
  ],

  fileTools: [
    {
      id: "f1",
      name: "Convert to ZIP",
      description: "Convert files to ZIP archive",
      category: "file",
      slug: "convert-to-zip",
    },
    {
      id: "f2",
      name: "Extract ZIP",
      description: "Extract files from ZIP archives",
      category: "file",
      slug: "extract-zip",
      popular: true,
    },
    {
      id: "f3",
      name: "Convert to RAR",
      description: "Convert files to RAR archive",
      category: "file",
      slug: "convert-to-rar",
    },
    {
      id: "f4",
      name: "Extract RAR",
      description: "Extract files from RAR archives",
      category: "file",
      slug: "extract-rar",
    },
    {
      id: "f5",
      name: "File Merger",
      description: "Merge multiple files into one",
      category: "file",
      slug: "file-merger",
    },
    {
      id: "f6",
      name: "File Splitter",
      description: "Split large files into smaller ones",
      category: "file",
      slug: "file-splitter",
    },
    {
      id: "f7",
      name: "File Compressor",
      description: "Compress files to save space",
      category: "file",
      slug: "file-compressor",
    },
    {
      id: "f8",
      name: "File Encryptor",
      description: "Encrypt your sensitive files",
      category: "file",
      slug: "file-encryptor",
    },
    {
      id: "f9",
      name: "File Converter",
      description: "Convert between file formats",
      category: "file",
      slug: "file-converter",
      popular: true,
    },
    {
      id: "f10",
      name: "File Renamer",
      description: "Batch rename multiple files",
      category: "file",
      slug: "file-renamer",
    },
    {
      id: "f11",
      name: "File Organizer",
      description: "Organize files by type and date",
      category: "file",
      slug: "file-organizer",
    },
    { id: "f12", name: "File Recovery", description: "Recover deleted files", category: "file", slug: "file-recovery" },
  ],

  textTools: [
    {
      id: "t1",
      name: "Text Case Converter",
      description: "Convert text case easily",
      category: "text",
      slug: "text-case-converter",
    },
    {
      id: "t2",
      name: "Word Counter",
      description: "Count words, characters and paragraphs",
      category: "text",
      slug: "word-counter",
    },
    {
      id: "t3",
      name: "Text Diff Checker",
      description: "Compare two texts for differences",
      category: "text",
      slug: "text-diff-checker",
    },
    {
      id: "t4",
      name: "Lorem Ipsum Generator",
      description: "Generate placeholder text",
      category: "text",
      slug: "lorem-ipsum-generator",
    },
    {
      id: "t5",
      name: "Text Encoder/Decoder",
      description: "Encode or decode text",
      category: "text",
      slug: "text-encoder-decoder",
    },
    {
      id: "t6",
      name: "Markdown Editor",
      description: "Edit and preview markdown",
      category: "text",
      slug: "markdown-editor",
    },
    {
      id: "t7",
      name: "JSON Formatter",
      description: "Format and validate JSON",
      category: "text",
      slug: "json-formatter",
    },
    {
      id: "t8",
      name: "HTML Formatter",
      description: "Format and beautify HTML",
      category: "text",
      slug: "html-formatter",
    },
    { id: "t9", name: "CSV to JSON", description: "Convert CSV to JSON format", category: "text", slug: "csv-to-json" },
    {
      id: "t10",
      name: "JSON to CSV",
      description: "Convert JSON to CSV format",
      category: "text",
      slug: "json-to-csv",
    },
    {
      id: "t11",
      name: "Text Translator",
      description: "Translate text between languages",
      category: "text",
      slug: "text-translator",
    },
    {
      id: "t12",
      name: "Regex Tester",
      description: "Test regular expressions",
      category: "text",
      slug: "regex-tester",
    },
  ],
}

export function getToolBySlug(slug: string): Tool | undefined {
  const allTools = [...toolsData.pdfTools, ...toolsData.imageTools, ...toolsData.fileTools, ...toolsData.textTools]

  return allTools.find((tool) => tool.slug === slug)
}

